### ISSUE TITLE
How to avoid "not enough RAM" error on gpat_polygon 

### ISSUE THREAD

**Issue by pierreroudier** [Nowosad/geopat2#20]
I'm getting the following error using `gpat_polygon` on quite a large dataset:

```
Calculating statistics... OK
Signature length: 55
Calculating extents of polygons...     Not enough RAM to proceed!
```

Apart from getting more RAM (already running 32 Go RAM on my machine), is there any way to get around this (tiling ?)

**Comment by Nowosad** [comment]
Hi @pierreroudier, the gpat_polygon uses up to 4GB RAM (4096 MB RAM) as a default. However, you can increase this value with the m flag, for example:

gpat_polygon -i my_input.tif -e my_polys.tif -o my.output.txt -m 16384

The above code increases RAM use to 16GB. 
Let me know if that's helpful.

**Comment by pierreroudier** [comment]
@Nowosad Of course, it works, I should have RTFM! Sorry for wasting your time on that one -- closing.
