### ISSUE TITLE
Can't get `gpat_gridhis` to work with more than one layer of categorical data

### ISSUE THREAD

**Issue by pierreroudier** [Nowosad/geopat2#22]
Using the latest version of geopat2, I can't seem to get the multi-layers mode to work with `gpat_gridhis`. I've tried to use the command that is briefly mentioned in the manual, and get the following errors: 

```
$ gpat_gridhis -i landcover.tif -i forms.tif -o /tmp/test_gpat_gridhis -s prod -z 25 -f 25 -t 2
gpat_gridhis: excess option -i|--input=forms.tif

$ gpat_gridhis --input=landcover.tif -input=forms.tif -o /tmp/test_gpat_gridhis -s prod  -z 25 -f 25 -t 2
gpat_gridhis: excess option -i|--input=nput=forms.tif
```

**Comment by Nowosad** [comment]
geopat 2.0 does not accept more than one layer of categorical data.
