### ISSUE TITLE
Windows .exe link not working

### ISSUE THREAD

**Issue by kapprovalija** [Nowosad/geopat2#35]
Dear Sir, 
looks like http://sil.uc.edu webisite is down for almost two weeks now and I can't find anywhere else windows exe to download. Can you provide us with some mirror link please?

**Comment by Nowosad** [comment]
Dear @kapprovalija ,
the SIL website is back online. You can find the windows version of GeoPAT 2 at http://sil.uc.edu/cms/data/uploads/software_data/GPAT2/GPAT2setup.exe.

**Comment by Nowosad** [comment]
I've also added a download mirror - https://github.com/Nowosad/geopat2win/raw/master/GPAT2setup.exe
