### ISSUE TITLE
Full decomposition gpat_pointshis

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/geopat2#4]
system("gpat_pointshis -i data/geomorph.tif -o data/query_signature.txt -s fdec -z 64 -x 751960.498319564 -y 2096539.09643261")

For full decomposition, size has to be a power of two.

**Comment by Nowosad** [comment]
@jniesterowicz is this (https://github.com/Nowosad/geopat2/commit/603af21eea47dc634a9fcccb5fd482e9f78969fc) the fix for the gpat_pointshis issue?

**Comment by jniesterowicz** [comment]
Yes. I'm closing the issue.
